### ISSUE TITLE
Baud rate option

### ISSUE THREAD

**Issue by MrLazy99** [npiegdon/bed-inspector#11]
I've just tried to connect my printer via the latest release and i get a random string of characters, and no homing sequence, the printer doesn't respond to the application, but it will connect via pronterface with a baud rate of 250000, is this maybe a baud rate issue? and if so is it possible to vary the baud rate? 
![image](https://user-images.githubusercontent.com/59511984/82124122-eb7ccc80-9794-11ea-8930-d695e92f31b6.png)

**Comment by MrLazy99** [comment]
Ok, I've looked through the source code again and located the baud rate, unfortunately I am having difficulties compiling the program and honestly have little knowledge of code, maybe a suggestion for further developing the program is to allow a variable baud rate? In the mean time do you have any suggestions in where I can look to properly compile the program?

**Comment by npiegdon** [comment]
It should just take opening the project in the latest version of the free Visual Studio Community and clicking the green "Play" button on the toolbar.  During install, just make sure to include the ".NET desktop development" workload option.

**Comment by MrLazy99** [comment]
I had been trying to do it through VS code which had been giving build errors, it appears it was successful with the VS community version thank you.

**Comment by npiegdon** [comment]
Now that you can compile it, does changing the baud rate solve the problem?

**Comment by MrLazy99** [comment]
It does work, separate issue now when doing the "measure every". I'm using a cr10s pro, when it moves to the LHS it stops probing as the probe overhangs the bed and isn't triggered, so its waiting for the initial trigger before it probes that point therefore it pauses. should i raise this as a separate issue?

**Comment by npiegdon** [comment]
> should i raise this as a separate issue?

This sounds like #8 (or at least, the solution to #8 will also solve this problem), so you don't have to worry about adding another issue.  Thanks!

I will leave this one open until baud-rate is an option inside the app.  That's a pretty big omission.
