### ISSUE TITLE
allow input of bed dimensions in future version?

### ISSUE THREAD

**Issue by Careless** [npiegdon/bed-inspector#2]
would be cool to have an input field group that allows users to enter their bed dimensions and desired grid spacing so that it could be used on other/custom built printers with other bed sizes.

the grid spacing would allow the test to complete faster on larger print surfaces that may sometimes be used in conjunction with taller layer printing heights & line widths, as the deviation from point to point may be less critical on printers like that, but levelling to some degree with this application would still be welcome to those users.

Your app is a much better alternative to the solution in the 3DPrinterTool for Marlin (which I still like), or generating my own graph from a CSV/tabbed output in console (still decent, just bothersome, even with all the automation tools I've tried).

**Comment by depark88** [comment]
Having the ability to map a 235x235 and 300x300 bed would be Great!

**Comment by npiegdon** [comment]
This should be live in the latest release.  There are new boxes you can type any dimensions (in mm) you like. :D

**Comment by depark88** [comment]
Awesome! Thanks. I'll be using this once my printer is fixed. I'm just waiting for parts.

**Comment by depark88** [comment]
Dumb question, How do you get it to start the utility?
Thanks

**Comment by npiegdon** [comment]
Do you mean once you're already running the app?  In v1.2, click the "Measure every..." button.  That will start running the grid pattern based on the number in the box next to that button.

**Comment by depark88** [comment]
No, how to start the app. Thanks

**Comment by npiegdon** [comment]
Hmm, I might still be misunderstanding.  You should be able to:
1. Download **bed-inspector.exe** from the [latest release](https://github.com/npiegdon/bed-inspector/releases/latest) page.
2. Run it.
3. (If there is an error message, make sure you've got the [.NET 4.7.2 Runtime](https://dotnet.microsoft.com/download/dotnet-framework/net472) installed.)

**Comment by depark88** [comment]
Thanks, I figured it out last night. I hadn't seen the .exe file till then.
Thanks for the help and a great app.
Cheers
