### ISSUE TITLE
Enhancement: Port / Convert, possible separate branch / build for .net core builds 

### ISSUE THREAD

**Issue by ipatch** [npiegdon/bed-inspector#5]
When I first discovered this app from sifting through videos on youtube, I noticed the app was written in .net, and not knowing much about .net I soon found out that .net core apps can run on a variety of platforms, where .net framework apps are limited to Windows only.  I being a person who has a Raspberry Pi with Octoprint setup on it, it's quite convenient to be able to run an app on a box that's connected to printer, and for my particular use case X11 forwarding, VNC, or whatever method to work with GUI apps on a box that I have access to would make for a great convenience as opposed to spinning up a virtual machine to run a utility.

I did a little research on what it would take to port the .net framework code / logic to .net core code / logic to be able to eventually run on macos or GNU+Linux and it seems the bulk of the work would be converting the the GUI widgets from the Windows Form Designer to something that is compatible with mac and linux, so utilizing a framework such as [http://avaloniaui.net/](http://avaloniaui.net/) could do a bulk of the work, not saying it'd be easy as clicking some check boxes and running build, but I don't think it'd be too much work.  I checked several different GUI / universal _frameworks_ for building .net core apps on macos and linux and the [avaloniaui](http://avaloniaui.net/) framework seems the most fleshed out from what i could tell.

And I'm not saying the core build of the app needs to be a .net core app, but there could be a different branch within this project that supplies a .net core build of this app for people who would like to run this utility on mac or linux.

cheers 🍩

**Comment by npiegdon** [comment]
Just a few months ago, Microsoft [announced](https://devblogs.microsoft.com/dotnet/introducing-net-core-windows-forms-designer-preview-1/) a version of Windows Forms for .NET Core.  That would probably be the fastest/easiest migration path.

The "Controls included in Preview 1" section on that page seems to list everything the app uses, so it should be a direct conversion.

**Comment by ipatch** [comment]
had some time to look at what it would take to develop a cross platform version of this utility, and read up on that article you linked.

- the cross platform version of the win forms for .net core only works with the _preview_ version of visual studio on windows, it however does work with the community version of visual studio so that's a positive.  i'd prefer to use my native OS, but developing within a virtual will work for now.

also it's a bit dated of a [graphic](https://stackoverflow.com/a/52797571/708807) but using mono + gtk seems like it would be possible to develop and run the utility on all three major platforms.

**Comment by npiegdon** [comment]
It looks like the .NET Core version of Windows Forms has [made it into the live release](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#windows-forms) of Visual Studio 16.6 in the meantime since the article I linked before.

The note in this new link mentions that you still need to enable a setting to get it to show up, but now that it's available in the general release without needing to install anything else, it should be a lot easier to test out.  (That said, I haven't had a chance to try it yet.)

**Comment by ipatch** [comment]
cool for the fact that they merged into to the release channel, but the _Windows Forms_ and _WPF_ components are still only compatible with Windows only OSes, those specific libraries have been "ported" to work with dotnet core, but they will not work on a GNU+Linux or macOS operating system.

You don't even need a separate OS to test the functionality, try and build a self contained binary for either macOS or GNU+Linux with Visual Studio on Windows, and the publish operation will not complete, if you choose to not build a self contained library and use the "imported" libraries as runtime dependencies you will notice that on macOS there is no Windows Forms library for macOS.  All of this is based on my empirical testing, so if anything I'm stating please correct me or call me out, last thing I want to do is spread false information.

I posted [this link](https://stackoverflow.com/questions/56219066/netcore-3-0-0-framework-version-not-found-even-though-it-is-installed-in-macos) in my prior post which pretty much talks about the runtime dependency issue that I have mentioned.

##

### switching gears 🕹

I still haven't gotten the "auto probe" feature working last time i checked which was several months ago, so first on the pecking order for me is to try and get that working, where i can click the button in the app, and have it generate all the required heat map circles.  Once I get that figured out, I'll do some more research on porting the app from .net framework to .netcore, and then once the app is entirely .netcore based, but still using the windows only GUI components ie. win forms, then it's time to decouple the gui aspect of the app from the windows only libs, and try to use a more universal compatible lib.

I'm not sure what your schedule looks like, but I've allotted some time today to work with my printer 🎉, so hopefully i'll make some progress with the "auto probe" feature of the app.

**Comment by npiegdon** [comment]
Reading this (five days shy of) a year later, I finally see what you mean about .NET Core (now just ".NET 5") not giving automatic WinForms compatibility in macOS and Linux.  That's unfortunate.

Switching to Core did mean dropping the System.Numerics dependency (it's built in to the base framework now), which was nice.

And the new naming convention (dropping the "Core" part) seems to indicate it's probably the right answer moving forward.
