### ISSUE TITLE
now points on bedPicture (v1.3)

### ISSUE THREAD

**Issue by Guenda85** [npiegdon/bed-inspector#7]
Hi there,
just downloaded v1.3 of your software - unfortunately it doesn't draw the points accordingly - bedPicture stays black :-(

i'm using Creality CR-20 Pro with Marlin 2 software - connection is working and printer is moving and probing:

start
echo: External Reset
Marlin 2.0.4.4
echo: Last Updated: 2020-02-27 | Author: (CR-20 Pro)
echo:Compiled: Mar  4 2020
echo: Free Memory: 3248  PlannerBufferBytes: 1200
echo:SD card ok
echo:V76 stored settings retrieved (623 bytes; crc 13533)
echo:  G21    ; Units in mm (mm)
echo:  M149 C ; Units in Celsius
echo:; Filament settings: Disabled
echo:  M200 D1.75
echo:  M200 D0
echo:; Steps per unit:
echo: M92 X80.00 Y80.00 Z400.00 E97.00
echo:; Maximum feedrates (units/s):
echo:  M203 X500.00 Y500.00 Z5.00 E25.00
echo:; Maximum Acceleration (units/s2):
echo:  M201 X500.00 Y500.00 Z100.00 E5000.00
echo:; Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
echo:  M204 P500.00 R500.00 T500.00
echo:; Advanced: B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> J<junc_dev>
echo:  M205 B20000.00 S0.00 T0.00 J0.08
echo:; Home offset:
echo:  M206 X0.00 Y0.00 Z0.00
echo:; Auto Bed Leveling:
echo:  M420 S0 Z0.00
echo:  G29 W I0 J0 Z-1.00250
echo:  G29 W I1 J0 Z-0.08500
echo:  G29 W I2 J0 Z0.57250
echo:  G29 W I0 J1 Z-1.12250
echo:  G29 W I1 J1 Z-0.36250
echo:  G29 W I2 J1 Z0.52250
echo:  G29 W I0 J2 Z-1.27500
echo:  G29 W I1 J2 Z-0.30250
echo:  G29 W I2 J2 Z0.50250
echo:; Material heatup parameters:
echo:  M145 S0 H185 B45 F255
echo:  M145 S1 H240 B70 F255
echo:; PID settings:
echo:  M301 P21.73 I1.54 D76.55
echo:; LCD Contrast:
echo:  M250 C195
echo:; Z-Probe Offset (mm):
echo:  M851 X-43.00 Y-5.00 Z-2.90
echo:SD card ok
X:160.00 Y:122.00 Z:12.90 E:0.00 Count X:12800 Y:9760 Z:5160
Bed X: 117.00 Y: 117.00 Z: -0.00
X:160.00 Y:122.00 Z:12.90 E:0.00 Count X:12800 Y:9760 Z:5160
X:160.00 Y:122.00 Z:12.90 E:0.00 Count X:12800 Y:9760 Z:5160
Bed X: 117.00 Y: 117.00 Z: -0.00
X:160.00 Y:122.00 Z:12.90 E:0.00 Count X:12800 Y:9760 Z:5160

**Comment by Guenda85** [comment]
![2020-03-06 11_05_53-OVINO-IT10652 - TeamViewer](https://user-images.githubusercontent.com/45709724/76073852-9a817880-5f9a-11ea-8a12-4d8d27f53ae3.png)

**Comment by npiegdon** [comment]
Thanks for the debugger screenshot!  I would have been scratching my head forever without it.

Would you happen to know what your computer's regional settings are for number separators?

It looks like it's parsing "117.00" as "11700", which might happen if it was using a decimal thousands separator (in a sloppy way without really verifying, since there should be three digits after it) instead of a comma separator.

So it's most-likely parsing the point, but then throwing it away when it's wayyy outside of your printer's bed bounds.

At this point I've seen printer output not match the OS in both directions from various users.  The right answer is probably to just offer an option.  But, a quick way to test that this is the root cause in the meantime would be to add the following around line 143:
```C#
s = s.Replace('.', ',');
```

Does that get the points drawing?

**Comment by Guenda85** [comment]
just gave it a try:
![2020-03-06 15_27_56-BedLeveler - Microsoft Visual Studio](https://user-images.githubusercontent.com/45709724/76092078-142b5d80-5fbf-11ea-8365-71fbf5ba5a16.png)

before: "Bed X: 117.00 Y: 117.00 Z: -0.01"
after: "Bed X: 117,00 Y: 117,00 Z: -0,01"

still doesn't draw the points

**Comment by Guenda85** [comment]
just did some debugging - after replacing "." with "," it does no longer parse properly.

i'm not that familiar with regex, but it looks like it doesn't match due to the us of ",":
![2020-03-06 15_34_48-BedLeveler (wird ausgeführt) - Microsoft Visual Studio](https://user-images.githubusercontent.com/45709724/76092682-1cd06380-5fc0-11ea-8e30-014f94da2c31.png)

**Comment by npiegdon** [comment]
Oh, try changing that `\.` near the middle of the matchFloat string over to a `,`.  Sorry, I missed that one.  It will discard them early without that.

**Comment by Guenda85** [comment]
that's it :-D thank you very much for your quick support!

![2020-03-06 15_40_29-Printer Bed Inspector 1 3](https://user-images.githubusercontent.com/45709724/76093233-ed6e2680-5fc0-11ea-8e05-fa744ef34e6f.png)
