### ISSUE TITLE
no colored circle

### ISSUE THREAD

**Issue by hliebscher** [npiegdon/bed-inspector#9]
Hi 

i have Marlin 2.0 and the Probe works but i get no circle in the black area...

X:150.00 Y:148.00 Z:5.00 E:0.00 Count A:23840 B:160 Z:4800
Bed X: 140.00 Y: 147.00 Z: 0.00
X:150.00 Y:148.00 Z:1.16 E:0.00 Count A:23840 B:160 Z:1109
Bed X: 73.00 Y: 79.00 Z: 0.03
X:83.00 Y:80.00 Z:1.18 E:0.00 Count A:13040 B:240 Z:1129
Bed X: 84.00 Y: 84.00 Z: 0.00
X:94.00 Y:85.00 Z:1.15 E:0.00 Count A:14320 B:720 Z:1103
Bed X: 84.00 Y: 84.00 Z: 0.00
X:94.00 Y:85.00 Z:1.15 E:0.00 Count A:14320 B:720 Z:1105

win10 visual studio 2019

**Comment by hliebscher** [comment]
i found a Problem with 

parsing m.Groups["x"].Value
NumberFormat.NumberDecimalSeparator
it works not

**Comment by npiegdon** [comment]
From now on it should parse all data from the printer using both decimal separators and keep whichever result worked best.  So hopefully this will work in every OS locale using any printer locale.
